//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcadePointsBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class L10n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal L10n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcadePointsBot.Resources.L10n", typeof(L10n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Action_Duplicate {
            get {
                return ResourceManager.GetString("Action_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration milliseconds.
        /// </summary>
        public static string Action_Duration {
            get {
                return ResourceManager.GetString("Action_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key action type.
        /// </summary>
        public static string Action_Key_Type {
            get {
                return ResourceManager.GetString("Action_Key_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard key.
        /// </summary>
        public static string Action_Keyboard_Key {
            get {
                return ResourceManager.GetString("Action_Keyboard_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Action Type.
        /// </summary>
        public static string Action_Mouse_Action {
            get {
                return ResourceManager.GetString("Action_Mouse_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse button.
        /// </summary>
        public static string Action_Mouse_Key {
            get {
                return ResourceManager.GetString("Action_Mouse_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Type.
        /// </summary>
        public static string Action_Type {
            get {
                return ResourceManager.GetString("Action_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        public static string Create_AddBtn {
            get {
                return ResourceManager.GetString("Create_AddBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category/Game.
        /// </summary>
        public static string Create_Category {
            get {
                return ResourceManager.GetString("Create_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Create_Cost {
            get {
                return ResourceManager.GetString("Create_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Reward.
        /// </summary>
        public static string Create_CreateBtn {
            get {
                return ResourceManager.GetString("Create_CreateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Require User Input.
        /// </summary>
        public static string Create_RequireInput {
            get {
                return ResourceManager.GetString("Create_RequireInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Title.
        /// </summary>
        public static string Create_Title {
            get {
                return ResourceManager.GetString("Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Reward.
        /// </summary>
        public static string Create_Window {
            get {
                return ResourceManager.GetString("Create_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string Edit_SaveBtn {
            get {
                return ResourceManager.GetString("Edit_SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reward.
        /// </summary>
        public static string Edit_Window {
            get {
                return ResourceManager.GetString("Edit_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Main_CB_Enabled {
            get {
                return ResourceManager.GetString("Main_CB_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Main_DeleteBtn {
            get {
                return ResourceManager.GetString("Main_DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Main_EditBtn {
            get {
                return ResourceManager.GetString("Main_EditBtn", resourceCulture);
            }
        }
    }
}
